function [ response,delay,error ] = database_connect_nominet(lat,long,my_path)
%DATABASE_CONNECT_NOMINET Summary of this function goes here
%   Detailed explanation goes here

error=false; %Default error value
delay=[]; %Default delay value

server_name='https://wsdb.org.uk:8081/paws';
text_coding='"Content-Type: application/json; charset=utf-8"';

%Query params
type = 'AVAIL_SPECTRUM_REQ';
version = '1.0';
serial_num = '1416580565120';
m_id = 'Nominet';
model_id = 'JS test client';
semiMajorAxis = '0';
height = '30';
heightType = 'AGL';
heightUncertainty = '10';
id = '2';
rulesetIds = 'ETSI-EN-301-598-1.1.1';
etsiEnDeviceType = 'A';
etsiEnDeviceCategory = 'master';
etsiEnDeviceEmissionsClass = '5';
etsiEnTechnologyId = 'DUMMY';
%%
nominet_query(lat,long,type,version,serial_num,m_id,model_id, semiMajorAxis,height,...
    heightType,heightUncertainty,id,rulesetIds, etsiEnDeviceType,...
    etsiEnDeviceCategory, etsiEnDeviceEmissionsClass,etsiEnTechnologyId);

cmnd=['/usr/bin/curl -X POST ',server_name,' -H ',text_coding,' --data-binary @',my_path,'/nominet.json -w %{time_total}'];
[status,response]=system(cmnd);

start_res = findstr('{' , response);
if ~isempty(start_res)
response = response(start_res(1):end);
end

error_str = findstr('error' , response);
if ~isempty(error_str)
   error=true; 
end

end_query_str=',"jsonrpc":"2.0"}';
pos_end_query_str=findstr(response,end_query_str);
length_end_query_str=length(end_query_str); 
delay=str2num(response(pos_end_query_str+length_end_query_str:end));
response(pos_end_query_str+length_end_query_str:end)=[];

system('rm nominet.json');
end
function nominet_query(lat,long,type,version,serial_num,m_id,model_id, semiMajorAxis,height,...
    heightType,heightUncertainty,id,rulesetIds, etsiEnDeviceType,...
    etsiEnDeviceCategory, etsiEnDeviceEmissionsClass,etsiEnTechnologyId);

request=['{"jsonrpc": "2.0",'...
'"method": "spectrum.paws.getSpectrum",'...
'"params": {'...
'"type": "',type,'",'...
'"version": "',version,'",'...
'"deviceDesc": {'...
'"serialNumber": "',serial_num,'",'...
'"manufacturerId": "',m_id,'",'...
'"modelId": "',model_id,'",'...
'"rulesetIds": ['...
'"',rulesetIds,'"],'...
'"etsiEnDeviceType": "',etsiEnDeviceType,'",'...
'"etsiEnDeviceCategory": "',etsiEnDeviceCategory,'",'...
'"etsiEnDeviceEmissionsClass": "',etsiEnDeviceEmissionsClass,'",'...
'"etsiEnTechnologyId": "',etsiEnTechnologyId,'"},'...
'"location": {"point": {"center": {'...
'"latitude": ' , num2str(lat) , ' , '...
'"longitude": ' , num2str(long) , ' },'...
'"semiMajorAxis": ',semiMajorAxis,'}},'...
'"antenna": {'...
'"height": ',height,','...
'"heightType": "',heightType,'",'...
'"heightUncertainty": ',heightUncertainty,'}},'...
'"id": ',id...
'}'];
dlmwrite('nominet.json',request,'');

end


