function [response,delay,error]=database_connect_microsoft(Longitude,Latitude,...
    PropagationModel,CullingThreshold,IncludeNonLicensed,...
    IncludeMicrophones,UseSRTM,UseGLOBE,UseLRBCast,my_path)
%DATABASE_CONNECT_MICROSOFT Script used in querying Microsoft WSDB [1].
%
%   Reference: [1] Will Dynamic Spectrum Access Drain my Battery?

%   Code development: 

%   Last update: 22 May 2014

%   This work is licensed under a Creative Commons Attribution 3.0 Unported
%   License. Link to license: http://creativecommons.org/licenses/by/3.0/

error=false; %Default error value
delay=[]; %Default delay value

username='przemek'; %[replace by your own]
passwd='TUD3lfT'; %[replace by your own]

microsoft_query(username,passwd,Longitude,Latitude,PropagationModel,...
    CullingThreshold,IncludeNonLicensed,IncludeMicrophones,UseSRTM,...
    UseGLOBE,UseLRBCast);

server_name='"whitespaces.msresearch.us/WSWeb/driver.asmx"';
text_coding='"content-type: text/xml; charset=utf-8"';

my_path=regexprep(my_path,' ','\\ ');

cmnd=['/usr/bin/curl --header',' ',text_coding,' --data-binary @',my_path,'/soap.xml',' ',server_name,' -w %{time_total}'];

[status,response]=system(cmnd);

warning_microsoft='Server was unable to process request';

if ~isempty(findstr(response,warning_microsoft));
    error=true;
    'Microsoft Error'
else
    end_query_str='</soap:Envelope>';
    pos_end_query_str=findstr(response,end_query_str);
    length_end_query_str=length(end_query_str);
    delay=str2num(response(pos_end_query_str+length_end_query_str:end));
    response(pos_end_query_str+length_end_query_str:end)=[];
end
system('rm soap.xml');

function microsoft_query(username,passwd,Longitude,Latitude,PropagationModel,...
    CullingThreshold,IncludeNonLicensed,IncludeMicrophones,UseSRTM,...
    UseGLOBE,UseLRBCast)

request=['<?xml version="1.0" encoding="utf-8"?>',...
'<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">',...
'<soap:Header>',...
'<AuthHeader xmlns="http://tempuri.org/">',...
'<username>',username,'</username>',...
'<passwd>',passwd,'</passwd>',...
'</AuthHeader>',...
'</soap:Header>',...
'<soap:Body>',...
'<GetSpectrumMap xmlns="http://tempuri.org/">',...
'<Latitude>',Latitude,'</Latitude>',...
'<Longitude>',Longitude,'</Longitude>',...
'<PropagationModel>',PropagationModel,'</PropagationModel>',...
'<CullingThreshold>',CullingThreshold,'</CullingThreshold>',...
'<IncludeNonLicensed>',IncludeNonLicensed,'</IncludeNonLicensed>',...
'<IncludeMicrophones>',IncludeMicrophones,'</IncludeMicrophones>',...
'<UseSRTM>',UseSRTM,'</UseSRTM>',...
'<UseGLOBE>',UseGLOBE,'</UseGLOBE>',...
'<UseLRBCast>',UseLRBCast,'</UseLRBCast>',...
'</GetSpectrumMap>',...
'</soap:Body>',...
'</soap:Envelope>'];

dlmwrite('soap.xml',request,'');